# Site
name: "USTH Coders Club Blog"
title: "UCC Blog"
description: "Chia sẻ về lập trình"
logo: "assets/images/logo_fixed.png"
favicon: "assets/images/icon_round_32.png"
baseurl: ""
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
include: ["_pages"]
permalink: /:title/
url: https://usth-coders-club.github.io

# Authors
authors:
    sal:
        name: Sal
        display_name: Sal
        gravatar: e56154546cf4be74e393c62d1ae9f9d4
        email: wowthemesnet@gmail.com
        web: https://www.wowthemes.net
        twitter: https://twitter.com/wowthemesnet
        description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
    john:
        name: John
        display_name: John
        avatar: "assets/images/avatar/avatar.png"
        gravatar: b1cc14991db7a456fcd761680bbc8f81
        email: wowthemesnet@gmail.com
        web: https://www.wowthemes.net
        twitter: https://twitter.com/wowthemesnet
        description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
    rylie:
        name: "Nguyễn Phạm Quốc An"
        display_name: "Nguyễn Phạm Quốc An"
        avatar: "assets/images/avatar/Aqukinn.png"
        web: https://j1nxie.github.io
        twitter: https://twitter.com/_lumi9
        description: "UCC Gen2 RnD member."
    tung:
        name: "Nguyễn Thanh Tùng"
        display_name: "Nguyễn Thanh Tùng"
        email: "tungnt.bi12-473@st.usth.edu.vn"
        description: "UCC Gen 2 RnD member."
    nhatthanh:
        name: "Đỗ Nhật Thành"
        display_name: "Đỗ Nhật Thành"
        avatar: "assets/images/avatar/picklerick.jpg"
        gravatar: 64ecaecdaf5d947ee0cddb3168087b0d
        email: "thanhdn.bi12-416@st.usth.edu.vn"
        web: "https://thanlanslab.wordpress.com/"
        description: "UCC Gen2 RnD member."
    Ph1eu:
        name: "Phạm Minh Hiếu"
        display_name: "Phạm Minh Hiếu"
        avatar: "assets/images/avatar/rengoku-ava.jpg"
        email: "hieupm.bi11-090@st.usth.edu.vn"
        kaggle: "https://www.kaggle.com/ph1euvn"
        description: "UCC Gen2 RnD member."
    htung:
        name: "Nguyễn Hoàng Tùng"
        display_name: "Nguyễn Hoàng Tùng"
        avatar: "assets/images/avatar/tonguesten.png"
        email: "tung@tungsoft.net"
        itch: "https://tonguesten.itch.io/"
        description: "UCC Gen2 RnD member."
    khiem:
        name: "Phạm Đức Khiêm"
        display_name: "Phạm Đức Khiêm"
        email: "khiempd.ba12-095@st.usth.edu.vn"
        avatar: "assets/images/avatar/kurisu.jpg"
        description: "UCC Gen2 RnD member."
    vanquocan:
        name: "Văn Quốc An"
        display_name: "Văn Quốc An"
        description: "UCC Gen2 RnD member."

# Plugins
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives

# Archives
jekyll-archives:
    enabled:
        - categories
    layout: archive
    permalinks:
        category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
    - changelog.md
    - LICENSE.txt
    - README.md
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/